apps/archinyl_web/lib/archinyl_web/router.ex
defmodule ArchinylWeb.Router do
  use ArchinylWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ArchinylWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ArchinylWeb.Telemetry
    end
  end

  scope "/", ArchinylWeb do
    pipe_through :browser

    live "/library", LibraryLive, :library
    live "/collection", CollectionLive, :collection
    live "/records", RecordsLive, :record
    live "/artists", ArtistsLive, :artist
    live "/user", UserLive, :user

    resources "/registration", RegistrationController, only: [:new, :create]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    get "/go_to_collection:collection_id", SessionController, :collection
    get "/*path", SessionController, :empty_path
  end
end

apps/archinyl_web/lib/archinyl_web/views/layout_view.ex
defmodule ArchinylWeb.LayoutView do
  use ArchinylWeb, :view
end

apps/archinyl_web/lib/archinyl_web/templates/layout/app.html.eex
<%= @inner_content %>

apps/archinyl_web/lib/archinyl_web/templates/layout/app.html.leex
<%= @inner_content %>

apps/archinyl_web/lib/archinyl_web/templates/layout/live.html.heex
<%= @inner_content %>

apps/archinyl_web/lib/archinyl_web/templates/layout/live.html.leex
<%= @inner_content %>

apps/archinyl_web/lib/archinyl_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tag() %>
  <%= live_title_tag  "Archinyl", suffix: " · Phoenix Framework" %>
  <link rel="shortcut icon" href={Routes.static_path(@conn, "/favicon.ico" )} type="image/x-icon">
  <link rel="icon" href={Routes.static_path(@conn, "/favicon.ico" )} type="image/x-icon">
  <link rel="stylesheet" href={Routes.static_path(@conn, "/css/app.css" )} />
  <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/js/app.js" )}></script>
  <link href="./jquery.minipreview.css" rel="stylesheet">
  <script src="./jquery.minipreview.js"></script>
  <script src="https://rawgit.com/shaneapen/Image-Preview-for-Links/master/image_preview_for_links.js"></script>
  <script src="https://kit.fontawesome.com/c241e00631.js" crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar has-background-primary-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src={Routes.static_path(@conn, "/images/archinyl_logo.png" )} width="60" height="50">
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">

        <%= live_patch to: Routes.static_path(@conn, "/library"), class: "navbar-item" do %>
        <span class="icon-text">
          <span class="icon has-text-info">
            <i class="fas fa-archive"></i>
          </span>
          <span>Library</span>
        </span>
        <% end %>

        <%= live_patch to: Routes.static_path(@conn, "/records"), class: "navbar-item" do %>
        <span class="icon-text">
          <span class="icon has-text-info">
            <i class="fas fa-record-vinyl"></i>
          </span>
          <span>Records</span>
        </span>
        <% end %>

        <%= live_patch to: Routes.static_path(@conn, "/artists"), class: "navbar-item" do %>
        <span class="icon-text">
          <span class="icon has-text-info">
            <i class="fas fa-users"></i>
          </span>
          <span>Artists</span>
        </span>
        <% end %>

      </div>


      <div class="navbar-end">
        <%= if logged_in?(@conn) do %>

        <div class="navbar-item">
          <div class="buttons">
            <%=link(current_user(@conn).email, to: Routes.static_path(@conn, "/user"), class: "button") %>


            <%=link("Logout", to: Routes.session_path(@conn, :delete), method: :delete, class: "button is-danger") %>
          </div>
        </div>
        <%else%>
        <div class="navbar-item">
          <div class="buttons">
            <%= link("Login", to: "/login", method: :get, class: "button is-link")%>
            <%= link("Register", to: Routes.registration_path(@conn, :new), method: :get, class: "button is-link is-light")%>
          </div>
        </div>

        <%end %>

      </div>
    </div>
  </nav>

  <div class="container is-fluid">
    <section class="section">
      <%= @inner_content %>
    </section>
  </div>
</body>

</html>

apps/archinyl_web/lib/archinyl_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tag() %>
  <%= live_title_tag  "Archinyl", suffix: " · Phoenix Framework" %>
  <link rel="shortcut icon" href="<%=Routes.static_path(@conn, "/favicon.ico")%>" type="image/x-icon">
  <link rel="icon" href="<%=Routes.static_path(@conn, "/favicon.ico")%>" type="image/x-icon">
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="<%=Routes.static_path(@conn, "/images/archinyl_logo.png")%>" width="60" height="50">
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item is-uppercase has-text-weight-bold">
          <%= live_patch to: Routes.static_path(@conn, "/library"), class: "navbar-item" do %>
          <span class="icon-text">
            <span class="icon has-text-info">
              <i class="fas fa-archive"></i>
            </span>
            <span>Library</span>
          </span>
          <% end %>
        </a>

        <a class="navbar-item is-uppercase has-text-weight-bold">
          <%= live_patch to: Routes.static_path(@conn, "/records"), class: "navbar-item" do %>
          <span class="icon-text">
            <span class="icon has-text-info">
              <i class="fas fa-record-vinyl"></i>
            </span>
            <span>Records</span>
          </span>
          <% end %>
        </a>
      </div>
      <div class="navbar-end">
        <%= if logged_in?(@conn) do %>
        <a class="navbar-item">
          <p><%= current_user(@conn).email %></p>
        </a>
        <a class="navbar-item">
          <p><%= link "Logout", to: ArchinylWeb.Router.Helpers.session_path(@conn, :delete), method: :delete %></p>
        </a>
        <% else %>
        <a class="navbar-item">
          <p><%= link "Login",    to: "/login" %></p>
        </a>
        <a class="navbar-item">
          <p style="margin-right: 0.5rem">
            <%= link "Register", to: ArchinylWeb.Router.Helpers.registration_path(@conn, :new) %></p>
        </a>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container is-fluid">
    <section class="section">
      <%= @inner_content %>
    </section>
  </div>
</body>

</html>